<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8">
        <title>Drips :: Debugger</title>
        <!-- jQuery -->
        <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
        <!-- Highlight.js -->
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/styles/github-gist.min.css"/>
        <script src="http://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.2.0/highlight.min.js"></script>
        <script type="text/javascript">
            $(document).ready(function () {
                $('pre code').each(function (i, block) {
                    hljs.highlightBlock(block);
                });
            });
        </script>
        <style>
            @import url(https://fonts.googleapis.com/css?family=Maven+Pro);

            body {
                margin: 0;
                padding: 0 10px;
                font-family: 'Maven Pro', sans-serif;
                background-color: #434a54;
            }

            .container {
                margin: 10px;
            }

            #logo-container {
                margin: 25px 0;
                text-align: center;
            }

            #logo {
                height: 60px;
            }

            .hljs-string {
                color: #183691;
            }

            .highlight {
                background-color: #e9573f;
                padding: 2px 0 1px 0;
                display: block;
                margin-bottom: -14px;
            }

            .highlight *, .highlight {
                color: white;
            }

            code {
                font-family: Consolas, "Liberation Mono", Menlo, Courier, monospace;
                font-size: 14px;
                background-color: #f5f7fa !important;
            }

            pre {
                margin: 0;
            }

            .error {
                margin: 20px auto;
                box-shadow: 0 0 8px 1px #353535;
            }

            .error > header {
                background-color: #e9573f;
                color: white;
            }

            .error > header > h1 {
                font-size: 20px;
                margin: 0;
                padding: 5px;
            }

            .error > footer {
                background-color: #656d78;
                color: #f5f7fa;
                padding: 5px;
                font-size: 10px;
            }

            .error > footer > p {
                margin: 0;
            }

            .error > footer > span {
                float: right;
                font-weight: bold;
            }

            #copyright {
                text-align: center;
                color: #656d78;
            }

            #copyright a {
                color: #656d78;
                text-decoration: none;
            }

            #copyright a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <div class="container">
            <div id="logo-container">
                <img id="logo" src="data:image/png;base64,<?= @base64_encode(file_get_contents(__DIR__."/drips.png")); ?>"/>
            </div>
            <?php foreach(\Drips\Debugger\Handler::getErrors() as $error): ?>
                <div class="error">
                    <header>
                        <h1>[<?= $error["number"] != 0 ? "ERROR#".$error["number"] : get_class($error["context"]); ?>]: <?= $error["desc"] ?></h1>
                    </header>
                    <?= $this::getCode($error["file"], $error["line"]); ?>
                    <footer>
                        <span>Line: <?= $error["line"] ?></span>
                        <p><?= $error["file"] ?></p>
                    </footer>
                </div>
            <?php endforeach; ?>
            <p id="copyright">Drips-Debugger :: powered by <a href="http://prowect.com" target="_blank">Prowect</a></p>
        </div>
    </body>
</html>
